### ISSUE TITLE
bank-statement

### ISSUE THREAD

**Issue by pekindenis** [jfk9w-go/homebot#1]
Добрый день @jfk9w, вы больше не занимаетесь разработкой [этого](https://pkg.go.dev/github.com/jfk9w-go/bank-statement#section-readme) пакета ? 

Подскажите, есть ли альтернативы которые вы используете ?
 
Хотел использовать экспорт из банкингов в локальную базу и по этим данным строить отчеты, авторизацию confirmation code можно организовать через телеграмм бота.

**Comment by jfk9w** [comment]
Добрый день! Того репозитория больше нет, есть https://github.com/jfk9w-go/homebot - позволяет синхронизировать данные по операциям из тинькова как раз с помощью телеграм-бота :) Однако поддерживается только тиньков, зато модель повторяет их апишную. Документации либо нет, либо она скорее всего не соответствует действительности, к сожалению, но самого бота в личных целях я использую. Если нужно, могу дописать документацию сегодня-завтра.

**Comment by jfk9w** [comment]
На самом деле могу еще примеры дашбордов в графане дать, я аналогичным образом данные в базу сливаю и дашборды по ним строю.

**Comment by pekindenis** [comment]
> Добрый день! Того репозитория больше нет, есть https://github.com/jfk9w-go/homebot - позволяет синхронизировать данные по операциям из тинькова как раз с помощью телеграм-бота :) Однако поддерживается только тиньков, зато модель повторяет их апишную. Документации либо нет, либо она скорее всего не соответствует действительности, к сожалению, но самого бота в личных целях я использую. Если нужно, могу дописать документацию сегодня-завтра.

Вау, отличный бот, как раз то что надо !!!

**Comment by pekindenis** [comment]
> На самом деле могу еще примеры дашбордов в графане дать, я аналогичным образом данные в базу сливаю и дашборды по ним строю.

О, давай. Можешь прикрепить сюда либо в телегу [мне](https://t.me/gipperionx) скинуть

**Comment by jfk9w** [comment]
@pekindenis [лови](https://github.com/jfk9w-go/homebot/tree/master/dashboards)
Если уже используешь бота, обнови его, пожалуйста – я добавил создание вьюх, необходимых для дашбордов.
Ну и ознакомься с обновленным [README](https://github.com/jfk9w-go/homebot/blob/master/README.md) :)

**Comment by pekindenis** [comment]
> @pekindenis [лови](https://github.com/jfk9w-go/homebot/tree/master/dashboards) Если уже используешь бота, обнови его, пожалуйста – я добавил создание вьюх, необходимых для дашбордов. Ну и ознакомься с обновленным [README](https://github.com/jfk9w-go/homebot/blob/master/README.md) :)

Спасибо, отличное решение !!! 
Когда делал проверку конфига обнаружил что печатается конфиг не со всеми опциями, для tinkoff секции не хватает параметров enabled  и receipts . 

А загрузка чеков работает ? Выставил параметр receipts: true, но таблица shopping_receipts пустая.

**Comment by pekindenis** [comment]
@jfk9w , подскажи как ты наполняешь таблицу [gps](https://github.com/jfk9w-go/homebot/blob/master/hassgpx/sql_storage.go ) из Home Assistant ? 
Используешь какую-то интеграцию или настроил recorder для hass который пишет сенсоры device_tracker в postgres ?
Поделись примером конфигурации :)

**Comment by jfk9w** [comment]
@pekindenis 

> Когда делал проверку конфига обнаружил что печатается конфиг не со всеми опциями, для tinkoff секции не хватает параметров enabled и receipts .

В шаблоне конфигурации выводятся только обязательные поля с пустыми значениями + поля с дефолтными значениями. Лучше все-таки посматривать в схему при составлении конфигурации :)

> А загрузка чеков работает ? Выставил параметр receipts: true, но таблица shopping_receipts пустая.

Пофиксил, но если данных много, есть большая вероятность, что упрется в rate limit на стороне тинькова – а он остывает ооооооочень долго (и я не знаю его характеристик, они его вроде недавно добавили).

> подскажи как ты наполняешь таблицу [gps](https://github.com/jfk9w-go/homebot/blob/master/hassgpx/sql_storage.go) из Home Assistant ?

Это просто вьюха, заполняется на основе данных из таблицы `states` хасса. Добавил автоматическое создание при старте бота.

> Используешь какую-то интеграцию или настроил recorder для hass который пишет сенсоры device_tracker в postgres ?

На самом деле мне так и не удалось нормально писать трек через Home Assistant. Я крутил разные ручки-сенсоры в приложении на андроиде, но он упорно не хотел отстреливать геолокацию с удобоваримой частотой (я вроде хотел, чтобы раз в 20-30 секунд хотя бы было). С OwnTracks у меня тоже что-то не взлетело. 

> Поделись примером конфигурации :)

Никакой специальной настройки для треков на серваке с hass вроде не делал, кроме собственно интеграции с мобильным приложением hass. Или ты не про эту конфигурацию? :)

Вообще, если есть идеи, как заставить хасс стрелять локацию с мобилки с заданным интервалом, буду рад услышать и, возможно, потестить :) Я так-то последний раз пытался год назад, у них с тех пор обновлялось приложение, так что когда наконец открою велосипедный сезон нормально, возможно, вернусь к этому вопросу.

**Comment by pekindenis** [comment]
@jfk9w 
>Пофиксил, но если данных много, есть большая вероятность, что упрется в rate limit на стороне тинькова – а он остывает ооооооочень долго (и я не знаю его характеристик, они его вроде недавно добавили).

Эх, нарвался на rate limit, в логах получил rate limit exceeded, retrying exchange :) 
После этого я отключил подгрузку чеков, сделал truncate базы операций и попробовал заново обновиться без чеков, все транзакции импортнулись, у меня там 6к записей :)
Наверное есть смысл при самом первом импорте если подгружаются чеки, делать задержку между запросами :)  

>Вообще, если есть идеи, как заставить хасс стрелять локацию с мобилки с заданным интервалом, буду рад услышать и, возможно, потестить :) Я так-то последний раз пытался год назад, у них с тех пор обновлялось приложение, так что когда наконец открою велосипедный сезон нормально, возможно, вернусь к этому вопросу.

Можно попробовать вместо прилы хасс использовать интеграцию с [Google Maps](https://www.home-assistant.io/integrations/google_maps) или [Life360](https://www.home-assistant.io/integrations/life360/).
Ну в этом случае данные будут отправляться на сторонние сервисы а сервер хасс будет их пулить. 
Так что не самое лучшее решение :)

**Comment by jfk9w** [comment]
> Наверное есть смысл при самом первом импорте если подгружаются чеки, делать задержку между запросами :)

Там все не так просто, у меня есть ощущение, что у них либо плавающие окна для рейт лимита, либо интервал чуть ли не больше даже дня. Отладка занимает кучу времени, а растягивать загрузку на сутки и дольше не хочется.

Вчера еще посмотрел – у них есть эндпойнт, который позволяет делать батчевые запросы, но проблема в том, что рейт лимит, похоже, срабатывает на каждый запрос из батча. Возможно, если руки дойдут, сделаю более умную загрузку чеков, но пока польза от них (кроме голого интереса к данным) для меня не очень очевидна – они были запилены, просто потому что тогда еще не было рейт лимита и это было просто :)

> Ну в этом случае данные будут отправляться на сторонние сервисы а сервер хасс будет их пулить.

Ну да, идея как раз в том, чтобы избежать отдачи данных во внешние сервисы. Так-то можно и просто на телефон трек писать через какой-нибудь AGPS-Tracker.

**Comment by pekindenis** [comment]
> Пофиксил, но если данных много, есть большая вероятность, что упрется в rate limit на стороне тинькова – а он остывает ооооооочень долго (и я не знаю его характеристик, они его вроде недавно добавили).

Я вот про остыв лимита не очень понял, я думал что он (лимит) привязывается к сессии, т.е после того как я его словил с чеками, выключив чеки, я смог при повторном запросе (с новой сессией) загрузить все транзакции с нуля. (предварительно очистив таблицу всех транзакций, у меня там их около 6к с 2016 года). 

Если лимит привязывать к юзеру, по логике, должен быть какой-то потолок rps который должен отрабатывать стабильно, иначе если бы я словил рейт лимит, то не смог бы зайти даже в банкинг после этого. 

Хотя, ты писал про интервалы с плавающими окнами, не знаю правильно ли я тебя понял, но предполагаю что есть окно интервала времени с кол-вом запросов за это время, ну и возможно некий потолок rps по всплеску который тоже ограничен в этом окне. И когда я загружал транзакции с нуля после попадания в лимит, я попал в новое окно. 
Я пытался проверить эту гипотезу, попробовав сделать после попадания в рейт лимит, загрузку транзакций без чеков в следующей сессии, она всегда проходит.

> Возможно, если руки дойдут, сделаю более умную загрузку чеков, но пока польза от них (кроме голого интереса к данным) для меня не очень очевидна – они были запилены, просто потому что тогда еще не было рейт лимита и это было просто :)

Есть еще идея строить динамику цен по основной корзине товаров из ежемесячных трат, наблюдать какие товары подорожали/подешевели, ну пока даже не знаю будет ли этот кейс полезен или нет :)

**Comment by jfk9w** [comment]
@pekindenis 

Обновил бота для соблюдения лимитов запросов по чекам и более умного обновления данных + добавил выгрузку локаций по операциям еще (обрати внимание, что из конфига пропала пара полей + операции нужно транкейтнуть, чтобы чеки смогли нормально загрузиться).
У меня получились примерно такие лимиты: 25 запросов в 75 секунд и 75 запросов в 11 минут (может быть не очень точно, но вроде работает ок – почти 400 чеков за один прогон он выгрузить смог, а дальше у меня ноут уснул, лол).
Свечи пока не синхронизируются, чуть позже допилю.
Также сделал сохранение токена в памяти и его пинг каждую минуту, пока не протухнет (на авторизацию ВНЕЗАПНО тоже есть рейт лимит, лол).

> Есть еще идея строить динамику цен по основной корзине товаров из ежемесячных трат, наблюдать какие товары подорожали/подешевели, ну пока даже не знаю будет ли этот кейс полезен или нет :)

Там в дашборде Expenses есть расчет Personal inflation rate – по идее с нужными фильтрами оно как раз и даст инфляцию по отдельно взятым продуктам.

**Comment by pekindenis** [comment]
> > Пофиксил, но если данных много, есть большая вероятность, что упрется в rate limit на стороне тинькова – а он остывает ооооооочень долго (и я не знаю его характеристик, они его вроде недавно добавили).
> 
> Я вот про остыв лимита не очень понял, я думал что он (лимит) привязывается к сессии, т.е после того как я его словил с чеками, выключив чеки, я смог при повторном запросе (с новой сессией) загрузить все транзакции с нуля. (предварительно очистив таблицу всех транзакций, у меня там их около 6к с 2016 года).
> 
> Если лимит привязывать к юзеру, по логике, должен быть какой-то потолок rps который должен отрабатывать стабильно, иначе если бы я словил рейт лимит, то не смог бы зайти даже в банкинг после этого.
> 
> Хотя, ты писал про интервалы с плавающими окнами, не знаю правильно ли я тебя понял, но предполагаю что есть окно интервала времени с кол-вом запросов за это время, ну и возможно некий потолок rps по всплеску который тоже ограничен в этом окне. И когда я загружал транзакции с нуля после попадания в лимит, я попал в новое окно. Я пытался проверить эту гипотезу, попробовав сделать после попадания в рейт лимит, загрузку транзакций без чеков в следующей сессии, она всегда проходит.
> 
> > Возможно, если руки дойдут, сделаю более умную загрузку чеков, но пока польза от них (кроме голого интереса к данным) для меня не очень очевидна – они были запилены, просто потому что тогда еще не было рейт лимита и это было просто :)
> 
> Есть еще идея строить динамику цен по основной корзине товаров из ежемесячных трат, наблюдать какие товары подорожали/подешевели, ну пока даже не знаю будет ли этот кейс полезен или нет :)

Спасибо за обнову, работает отлично !!! 

А ты чеки в Тинькоф сейчас вручную добавляешь или используешь какое-то решение ?

Было бы круто автоматизировать загрузку чеков )) Большенство магазинов сейчас чеки на почту присылают, если заказывать онлайн, можно их парсить, находить qr код и отправлять их через апишку в тинькоф.  
Хотя, можно в обход тинькова в текущую базу их добавлять, т.к данные уже под рукой. 

Правда если есть только бумажный чек, придется самому сканировать через прилу банка, либо написать бота который будет обрабатывать фотку чека )) 

Я заметил что некоторые магазины сразу в тинькоф чеки добавляют, возможно он подгружает их из какого-то сервиса, в который не все магазины отправляют данные. Хм, это наверное чеки от компаний которые используют тинькоф кассу.

**Comment by jfk9w** [comment]
> А ты чеки в Тинькоф сейчас вручную добавляешь или используешь какое-то решение ?

У меня чеки только те, что тиньков сам подгружает. Ради интереса попробовал добавить чеки по QR-коду из деливери клаба – работает, но как на постоянку такое решение прям не очень нравится.

> Я заметил что некоторые магазины сразу в тинькоф чеки добавляют, возможно он подгружает их из какого-то сервиса, в который не все магазины отправляют данные. Хм, это наверное чеки от компаний которые используют тинькоф кассу.

Я думаю, это больше связано с тем, с каким ОФД у тинькова есть соглашение. Вообще через API налоговой можно запрашивать чеки (непонятно, правда, какие именно), но апишка доступна только для ИП и юрлиц (а я свое ИП как раз закрыл недавно).

> Было бы круто автоматизировать загрузку чеков )) Большенство магазинов сейчас чеки на почту присылают, если заказывать онлайн, можно их парсить, находить qr код и отправлять их через апишку в тинькоф.
Хотя, можно в обход тинькова в текущую базу их добавлять, т.к данные уже под рукой.

В целом можно подумать, почту парсить всяко проще, чем бумажные чеки. Но тут могут возникнуть проблемы с привязкой к операциям. Нужно подумать.

**Comment by pekindenis** [comment]
> Я думаю, это больше связано с тем, с каким ОФД у тинькова есть соглашение. Вообще через API налоговой можно запрашивать чеки (непонятно, правда, какие именно), но апишка доступна только для ИП и юрлиц (а я свое ИП как раз закрыл недавно).

Теперь для физ лиц можно смотреть чеки в налоговом кабинете https://lkdr.nalog.ru/ . Там можно поковырять их апишку и оттуда получить все доступные чеки ))

**Comment by jfk9w** [comment]
@pekindenis FYI: запилил новый проект https://github.com/jfk9w/hoarder.
Умеет выгружать гораздо больше данных из Тинькова и чеки из ФНС.
Этот проект архивирую.
